# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bf73741098ecbe925d8a0f1a01c46e74209d31f6f92b2f5ac7ef97e577fe1cba74c7c87e092db4b9707f1dae44fb658f93f492f2cc2a79c542d97ddc51f94bec

test:
  secret_key_base: 838d0bba1bb049326e3fea78e7f011f066b32a04d46c911410c62bdeb46cc12c48f1670013fa4d34516d6674ab68603b3462d94df1961d54eb7aea3bd528f17f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
